name: SST Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: production

permissions: 
  contents: read
  deployments: write
  id-token: write

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    environment:
      name: CI
      url: https://reports.thecaringplace.info
    env:
      SST_PRINT_LOGS: 1
      SST_STAGE: production
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::677276093280:role/GitHubDeploy
          role-duration-seconds: 3600
          aws-region: us-east-2
      - name: Install Dependencies
        run: npm ci
      - name: Sync S3
        run: npm run sync-s3
        working-directory: packages/parser
      - name: Set SST Secrets
        run: | 
          npx sst secret set USERNAME ${{ secrets.USERNAME }}
          npx sst secret set PASSWORD ${{ secrets.PASSWORD }}
      - name: Build
        run: npm run build
      - name: Deploy app
        run: npm run deploy